version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  apigateaway:
    build:
      context: ./apiGateaway
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
